import js from "@eslint/js";
import * as tseslint from "typescript-eslint";
import prettier from "eslint-plugin-prettier";
import promise from "eslint-plugin-promise";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import sonarjs from "eslint-plugin-sonarjs";
import testcafe from "eslint-plugin-testcafe";
import testingLibrary from "eslint-plugin-testing-library";
import unicorn from "eslint-plugin-unicorn";
import unusedImports from "eslint-plugin-unused-imports";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import sortImportsEs6Autofix from "eslint-plugin-sort-imports-es6-autofix";
import sortKeysFix from "eslint-plugin-sort-keys-fix";
import importAlias from "eslint-plugin-import-alias";
import globals from "globals";

export default [
	{
		files: ["**/*.{js,ts,tsx}"],
		languageOptions: {
			parser: tseslint.parser,
			parserOptions: {
				ecmaFeatures: { jsx: true },
				ecmaVersion: "latest",
				sourceType: "module",
				project: "./tsconfig.eslint.json",
				tsconfigRootDir: new URL(".", import.meta.url).pathname,
				projectFolderIgnoreList: ["build", "coverage", "node_modules", "public", "dist", "src/tests/mocks"],
			},
			globals: {
				...globals.browser,
				...globals.node,
				...globals.vitest,
				React: true,
				NodeJS: true,
			},
		},
		settings: {
			react: { version: "detect" },
		},
		plugins: {
			"@typescript-eslint": tseslint.plugin,
			prettier,
			promise,
			react,
			"react-hooks": reactHooks,
			sonarjs,
			testcafe,
			"testing-library": testingLibrary,
			unicorn,
			"unused-imports": unusedImports,
			"simple-import-sort": simpleImportSort,
			"sort-imports-es6-autofix": sortImportsEs6Autofix,
			"sort-keys-fix": sortKeysFix,
			"import-alias": importAlias,
		},
		rules: {
			...js.configs.recommended.rules,
			...tseslint.configs.recommendedTypeChecked[0].rules,
			"@typescript-eslint/no-duplicate-type-constituents": "off",
			"@typescript-eslint/ban-ts-comment": "warn",
			"@typescript-eslint/no-restricted-types": "warn",
			"@typescript-eslint/consistent-type-definitions": ["error", "interface"],
			"@typescript-eslint/explicit-module-boundary-types": "warn",
			"@typescript-eslint/no-empty-function": ["warn", { allow: [] }],
			"@typescript-eslint/no-explicit-any": "warn",
			"@typescript-eslint/no-floating-promises": "off",
			"@typescript-eslint/no-misused-promises": "warn",
			"@typescript-eslint/no-non-null-assertion": "warn",
			"@typescript-eslint/no-unnecessary-condition": "warn",
			"@typescript-eslint/no-unsafe-argument": "warn",
			"@typescript-eslint/no-unsafe-assignment": "warn",
			"@typescript-eslint/no-unsafe-call": "warn",
			"@typescript-eslint/no-unsafe-member-access": "warn",
			"@typescript-eslint/no-unsafe-return": "warn",
			"@typescript-eslint/no-unsafe-enum-comparison": "warn",
			"@typescript-eslint/no-unused-expressions": [
				"warn",
				{
					allowShortCircuit: false,
					allowTernary: false,
					allowTaggedTemplates: false,
				},
			],
			"@typescript-eslint/await-thenable": "off",
			"@typescript-eslint/no-unused-vars": ["error", { varsIgnorePattern: "_" }],
			"@typescript-eslint/no-var-requires": "warn",
			"@typescript-eslint/prefer-regexp-exec": "warn",
			"@typescript-eslint/restrict-plus-operands": "warn",
			"@typescript-eslint/restrict-template-expressions": "warn",
			"@typescript-eslint/unbound-method": "warn",
			"arrow-body-style": ["error", "as-needed"],
			curly: "error",
			"max-lines": ["warn", { max: 300, skipBlankLines: true, skipComments: true }],
			"max-lines-per-function": ["warn", { max: 40, skipBlankLines: true, skipComments: true }],
			"no-negated-condition": "error",
			"no-nested-ternary": "error",
			"no-unneeded-ternary": "error",
			"no-unused-expressions": "off",
			"no-unused-vars": "off",
			"prefer-const": ["warn", { destructuring: "all" }],
			"prettier/prettier": ["off", { endOfLine: "auto" }],
			"promise/param-names": "warn",
			"react-hooks/rules-of-hooks": "error",
			"react/no-unknown-property": ["error", { ignore: ["css"] }],
			"react/prop-types": "off",
			"react/self-closing-comp": "error",
			"sonarjs/cognitive-complexity": "error",
			"sonarjs/no-all-duplicated-branches": "error",
			"sonarjs/no-collapsible-if": "error",
			"sonarjs/no-duplicate-string": ["error", { threshold: 5 }],
			"sonarjs/no-identical-expressions": "error",
			"sonarjs/no-identical-functions": "error",
			"sonarjs/no-small-switch": "error",
			"sonarjs/no-nested-template-literals": "warn",
			"sonarjs/prefer-single-boolean-return": "off",
			"sonarjs/no-one-iteration-loop": "off",
			"sort-keys-fix/sort-keys-fix": ["error", "asc", { caseSensitive: true }],
			"simple-import-sort/imports": "off",
			"simple-import-sort/exports": "off",
			"import-alias/import-alias": ["error", { relativeDepth: 0 }],
			"testing-library/await-async-queries": "warn",
			"testing-library/consistent-data-testid": "off",
			"testing-library/no-await-sync-events": "error",
			"testing-library/no-await-sync-queries": "error",
			"testing-library/no-dom-import": "error",
			"testing-library/no-node-access": "error",
			"testing-library/no-unnecessary-act": "error",
			"testing-library/no-wait-for-multiple-assertions": "error",
			"testing-library/no-wait-for-side-effects": "error",
			"testing-library/no-wait-for-snapshot": "error",
			"testing-library/prefer-explicit-assert": "error",
			"testing-library/prefer-find-by": "error",
			"testing-library/prefer-presence-queries": "error",
			"testing-library/prefer-user-event": "error",
			"unicorn/consistent-destructuring": "error",
			"unicorn/consistent-function-scoping": "error",
			"unicorn/error-message": "error",
			"unicorn/explicit-length-check": "error",
			"unicorn/filename-case": "warn",
			"unicorn/import-style": "error",
			"unicorn/no-abusive-eslint-disable": "error",
			"unicorn/no-array-callback-reference": "warn",
			"unicorn/no-array-for-each": "error",
			"unicorn/no-array-method-this-argument": "warn",
			"unicorn/no-array-reduce": "error",
			"unicorn/no-await-expression-member": "error",
			"unicorn/no-new-array": "error",
			"unicorn/no-null": "warn",
			"unicorn/no-object-as-default-parameter": "error",
			"unicorn/no-useless-undefined": ["error", { checkArguments: false }],
			"unicorn/prefer-array-some": "error",
			"unicorn/prefer-at": "off",
			"unicorn/prefer-module": "off",
			"unicorn/prefer-node-protocol": "off",
			"unicorn/prefer-number-properties": "error",
			"unicorn/prefer-prototype-methods": "error",
			"unicorn/prefer-spread": "error",
			"unicorn/prefer-string-slice": "error",
			"unicorn/prefer-ternary": "off",
			"unicorn/prefer-top-level-await": "error",
			"unicorn/prevent-abbreviations": ["error", { ignore: [{}, "i18n", "e2e"] }],
			"unicorn/prefer-blob-reading-methods": "warn",
		},
	},
	{
		files: ["**/*.d.ts"],
		rules: {
			"@typescript-eslint/no-unused-vars": "off",
			"unicorn/no-empty-file": "off",
		},
	},
	{
		files: ["**/e2e/**/*.ts", "**/cucumber/**/*.ts", "**/cucumber/**/*.feature"],
		rules: {
			"sort-keys-fix/sort-keys-fix": "off",
		},
	},
	{
		ignores: [
			"build/",
			"config-overrides.js",
			"coverage/",
			"dist/",
			"public/",
			"scripts/",
			"src/i18n",
			"src/resources/*",
			"src/tailwind.config.js",
			"src/tests",
			"vitest.setup.ts",
			"*.d.ts",
			"**/cucumber/**",
			"**/e2e/**",
			"**/utils/e2e-*.ts",
		],
	},
];
