name: Feature Request
description: Create a feature request for ARK Vault
title: '[Section] '
labels: ["web", "feature"]
body:
    - type: markdown
      attributes:
          value: Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.
    - type: textarea
      attributes:
          label: Describe the feature you'd like to request
          description: A clear and concise description of what you want.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Describe the feature requirements you'd like
          description: A clear and concise description of what you want to happen.
      validations:
          required: true
