export const CURRENCIES = {
	AUD: { decimals: 2, symbol: "A$" },
	BRL: { decimals: 2, symbol: "R$" },
	BTC: { decimals: 8, symbol: "Ƀ" },
	CAD: { decimals: 2, symbol: "C$" },
	CHF: { decimals: 2, symbol: "CHF" },
	CNY: { decimals: 2, symbol: "¥" },
	DKK: { decimals: 2, symbol: "dkr" },
	ETH: { decimals: 8, symbol: "Ξ" },
	EUR: { decimals: 2, symbol: "€" },
	GBP: { decimals: 2, symbol: "£" },
	HKD: { decimals: 2, symbol: "HK$" },
	IDR: { decimals: 2, symbol: "IDR" },
	INR: { decimals: 2, symbol: "₹" },
	JPY: { decimals: 0, symbol: "¥" },
	KRW: { decimals: 0, symbol: "₩" },
	LTC: { decimals: 8, symbol: "Ł" },
	MXN: { decimals: 2, symbol: "MX$" },
	NOK: { decimals: 2, symbol: "nkr" },
	RUB: { decimals: 2, symbol: "₽" },
	SEK: { decimals: 2, symbol: "skr" },
	USD: { decimals: 2, symbol: "$" },
	VND: { decimals: 0, symbol: "₫" },
};
