name: Compress

on:
    pull_request:
        paths:
            - "**.svg"

jobs:
    svg:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GH_TOKEN }}

            - uses: ericcornelissen/svgo-action@v1
              with:
                  conventional-commits: true
                  ignore: dist/**
                  repo-token: ${{ secrets.GH_TOKEN }}
