name: Dependencies

on:
    # schedule:
    #     - cron: "0 0 * * 0"
    workflow_dispatch:

jobs:
    js:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.12.2]

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GH_TOKEN }}

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm

            - name: Update JS dependencies
              run: npx npm-check-updates --configFilePath ./

            - name: Install Updated JS dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Rebuild Assets
              run: ZENDESK_WIDGET_KEY=${{ secrets.ZENDESK_WIDGET_KEY }} pnpm run build

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  commit-message: "chore: update JavaScript dependencies"
                  committer: GitHub <noreply@github.com>
                  author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                  branch: chore/update-javascript-dependencies
                  delete-branch: true
                  title: "chore: update JavaScript dependencies"
                  draft: false
