name: Format

on:
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    eslint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.12.2]

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GH_TOKEN }}

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm

            - name: Update System
              run: sudo apt-get update

            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev

            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile

            - name: Format
              run: pnpm format

            # - name: RustyWind
            #   run: |
            #     curl -LSfs https://avencera.github.io/rustywind/install.sh | sh -s -- --git avencera/rustywind
            #     rustywind --write .

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "style: resolve style guide violations"
                  branch: ${{ github.head_ref }}
