name: Test
on:
    push:
        branches:
            - master
            - develop
    pull_request:
        types:
            - ready_for_review
            - synchronize
            - opened
jobs:
    app:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/app
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-app
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/app
    domains-contact:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/contact
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-contact
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/contact
    domains-dashboard:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/dashboard
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-dashboard
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/dashboard
    domains-error:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/error
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-error
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/error
    domains-exchange:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/exchange
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-exchange
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/exchange
    domains-message:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/message
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-message
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/message
    domains-network:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/network
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-network
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/network
    domains-news:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/news
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-news
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/news
    domains-profile:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/profile
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-profile
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/profile
    domains-setting:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/setting
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-setting
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/setting
    domains-transaction:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/transaction
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-transaction
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/transaction
    domains-vote:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/vote
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-vote
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/vote
    domains-wallet:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/domains/wallet
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-domains-wallet
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/domains/wallet
    router:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/router
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-router
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/router
    utils:
        runs-on: ubuntu-latest
        env:
            COVERAGE_INCLUDE_PATH: src/utils
            COVERAGE_THRESHOLD: 25
        strategy:
            matrix:
                node-version:
                    - 16.17.1
        concurrency:
            group: ${{ github.head_ref }}-test-utils
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Update System
              run: sudo apt-get update
            - name: Install (Ledger Requirements)
              run: sudo apt-get install libudev-dev libusb-1.0-0-dev
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Rebuild
              run: pnpm rebuild
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 1
                  command: pnpm vitest run --coverage --dir src/utils
